version: '3.1'
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    volumes:
      - ./data/zoo3:/opt/persist
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2182 server.3=zoo3:2888:3888;2183
    networks:
      - zookeeper-solr

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    volumes:
      - ./data/zoo3:/opt/persist
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2182 server.3=zoo3:2888:3888;2183
    networks:
      - zookeeper-solr

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    volumes:
      - ./data/zoo3:/opt/persist
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2182 server.3=0.0.0.0:2888:3888;2183
    networks:
      - zookeeper-solr

  solr-1:
    image: solr
    restart: always
    ports:
        - 8981:8981
    volumes:
      - ./data/solr-1/logs:/opt/logs
      - ./data/solr-1/store:/store
    environment:
      SOLR_PORT: 8981
      SOLR_HOME: /store/solr
      ZK_HOST: zoo1:2181,zoo2:2182,zoo3:2183
      SOLR_LOGS_DIR: /opt/logs
      SOLR_HOST: solr-1
      SOLR_HEAP:
      SOLR_JAVA_MEM:
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - zookeeper-solr

  solr-2:
    image: solr
    restart: always
    ports:
      - 8982:8982
    volumes:
      - ./data/solr-2/logs:/opt/logs
      - ./data/solr-2/store:/store
    environment:
      SOLR_PORT: 8982
      SOLR_HOME: /store/solr
      ZK_HOST: zoo1:2181,zoo2:2182,zoo3:2183
      SOLR_LOGS_DIR: /opt/logs
      SOLR_HOST: solr-2
      SOLR_HEAP:
      SOLR_JAVA_MEM:
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - zookeeper-solr

  solr-3:
    image: solr
    restart: always
    ports:
      - 8983:8983
    volumes:
      - ./data/solr-3/logs:/opt/logs
      - ./data/solr-3/store:/store
    environment:
      SOLR_PORT: 8983
      SOLR_HOME: /store/solr
      ZK_HOST: zoo1:2181,zoo2:2182,zoo3:2183
      SOLR_LOGS_DIR: /opt/logs
      SOLR_HOST: solr-3
      SOLR_HEAP:
      SOLR_JAVA_MEM:
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - zookeeper-solr
  
networks:
  zookeeper-solr:
    driver: bridge